include:
  - path: compose/networks-volumes.yaml
    env_file: .env
  - path: compose/platform.yaml
    env_file: .env
  - path: compose/airflow.yaml
    env_file: .env
  - path: compose/spark.yaml
    env_file: .env
  - path: compose/mlflow.yaml
    env_file: .env
  - path: compose/metabase.yaml
    env_file: .env
